### ISSUE TITLE
Image browser panorama option not working

### ISSUE THREAD

**Issue by manassm** [GeorgLegato/sd-webui-panorama-viewer#18]
After the recent update of removing standalone panorama tab (which is supposedly convenient), pressing panorama button from image browser doesn't do anything. What can I do?

**Comment by GeorgLegato** [comment]
sorry for late answer, somehow I do not get notifications from github...

there is a decent break in SD-WebUI due to upgrade to gradio 3.23.0. Most extensions suffers from it.
Myself I, did a rollback to a former version of webui to commit a9eab236

```
git checkout a9eab236d7e8afa4d6205127904a385b2c43bb24
```

**Comment by gyy0611** [comment]
Hello, my click was also unresponsive. My version is a stable diffusion version from March 29th, which version should I download? The A9eab236 you mentioned cannot be found

**Comment by GeorgLegato** [comment]
meanwhile we are a new tagged version: 1.1 or commit id #5ab...
you need to updatr your sd-installation. 

open cmd
cd >your sd-path>
git pull

if any error about "local changes" bla: 
git commit -m"my changes" .

or install freshly, maybe best idea since a lot has changed 

![image](https://user-images.githubusercontent.com/7210708/236321294-dfdf3bb7-0929-49f2-8517-c8f9c4c8e1e0.png)

**Comment by GeorgLegato** [comment]
btw, there is permanent trouble with Firefox. I do not support it anymore, no chance, this browser is broken
