### ISSUE TITLE
'gradio' has no attribute 'UploadButton'

### ISSUE THREAD

**Issue by ludos1978** [GeorgLegato/sd-webui-panorama-viewer#33]
Hi, Running on Windows, i get the following error.

```
Error executing callback ui_tabs_callback for D:\stable-diffusion\AUTOMATIC1111-stable-diffusion-webui-master-2\extensions\sd-webui-panorama-viewer\scripts\panorama-3dviewer.py
Traceback (most recent call last):
  File "D:\stable-diffusion\AUTOMATIC1111-stable-diffusion-webui-master-2\modules\script_callbacks.py", line 95, in ui_tabs_callback
    res += c.callback() or []
  File "D:\stable-diffusion\AUTOMATIC1111-stable-diffusion-webui-master-2\extensions\sd-webui-panorama-viewer\scripts\panorama-3dviewer.py", line 35, in add_tab
    upload_button = gr.UploadButton("Upload movie...", file_types=["video"], file_count="single")
AttributeError: module 'gradio' has no attribute 'UploadButton'
```

edit: it works on osx, might be windows-python libraries

**Comment by GeorgLegato** [comment]
seems your sd webui auto1111 is outdated
check your commit version is that 22bbc like one.
often users have changed some file within auto1111, like webui-user.bat and did not commit it. that blocks forever git pull to update sdwebui

on cmd in auto1111 folder check
git status
if any modified stuff either revert change by
git checkout file

or commit your change
git commit -m"mychange" file

so that 

git pull

does not claim about local changes not be overwritten
